import Head from 'next/head'
import Image from 'next/image'
import ProductCard from '../components/productCard'


export default function Home(props:any) {

  return (
    <>
      <Head>
        <title>EShopNepal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={"/images/banners/banner1.webp"} style={{
        width:"100%",
        objectFit:"contain"
      }}
      priority
      width={100}
      height={100}
      sizes={"100vw"}
      alt='banner' /> 
      <section className="text-gray-600 body-font">
  <div className="container px-6 py-14 mx-auto">
    <h1 className='font-bold text-center text-2xl py-4'>Feature Products</h1>
    <div className="flex flex-wrap -m-4 justify-center ">
      {
        props.products.products != null && Object.keys(props.products.products).map((key:any,ind:any) => {
          return(
            <ProductCard
            key={ind}
            slug={"/product/"+props.products.products[key].slug}
            title={props.products.products[key].title}
            price={props.products.products[key].price}
            category={props.products.products[key].category}
            imgSrc={props.products.products[key].imgSrc}
            size ={props.products.products[key].size}
            />
          )
        })
      }
     
     
    </div>
  </div>
</section>
    </>   
  )
}

export const  getServerSideProps = async () => {
  let dev = process.env.NODE_ENV !== "production";
  let {DEV_URL,PROD_URL} = process.env;

  let res = await fetch(`${dev ? DEV_URL : PROD_URL}/api/products`);
  let products = await res.json();
  return{
    props:{
      products
    }
  }
}
